### ISSUE TITLE
Mouse Not clicking consistently on all clients

### ISSUE THREAD

**Issue by LiViXiSs** [osrsbots-com/ORB#1]
3 of 4 clients have no issues clicking in the same place everytime. However the 4th client takes up to 3 clicks for it to finally click on what it needs to. I have provided a video to the discord to better explain what is happening.

**Comment by osrsbots-com** [comment]
Noted - ORB's game interaction is currently lacking mouse accuracy, this issue is being investigated and I will report back when I have an update!

**Comment by osrsbots-com** [comment]
Mostly fixed in 0.2.5 BETA, more updates to mouse accuracy will follow - thanks for reporting!
