### ISSUE TITLE
Camera/compass movement is innacurate

### ISSUE THREAD

**Issue by Robstinator** [osrsbots-com/ORB#2]
When pressing or holding the left or right keys to move the camera/compass, The follower moves much more than the leader. This becomes an issue if you click somewhere on the map that is off camera for the follower. Edit: Holding middle mouse button and moving the mouse works much better for moving the camera though

**Comment by osrsbots-com** [comment]
I am able to reproduce this issue and it will be corrected when the time is available - for now I would suggest using 3rd mouse button (scroll wheel) to move the camera by clicking and dragging - Thanks for reporting!
