### ISSUE TITLE
Follower attacks monsters that are already being fought. 

### ISSUE THREAD

**Issue by Robstinator** [osrsbots-com/ORB#3]
So, combat is one thing that doesn't seem to work very well yet. Sometimes the follower will successfully attack, but often times it will try to attack something that is already being attacked by another player or it will just fail to attack anything at all. 
Edit: Sometimes if you click on the map in a certain spot, a follower may accidentally click on a monster and attack it. Not sure if there's any way to fix that though.

**Comment by osrsbots-com** [comment]
Fixed in 0.2.0 ALPHA with "Attacking" Toggle - Thanks for reporting!
