### ISSUE TITLE
World Flag 

### ISSUE THREAD

**Issue by LiViXiSs** [osrsbots-com/ORB#4]
World flag seeming to not work. 

I set 1st client world to --world:430 however the world it loads up with is world 480

This is not a huge priority for me.

**Comment by osrsbots-com** [comment]
We talked about this a bit in discord, I think this was only happening for sandboxed instances? I will look into this issue soon - Thanks for reporting!

**Comment by osrsbots-com** [comment]
Fixed in 0.3.0 BETA
