### ISSUE TITLE
[Bug] Chat bug

### ISSUE THREAD

**Issue by livixis** [osrsbots-com/ORB#9]
BUG: When enabling features in echo, Leader messages are in clan chat and follower messages are in public.

Where: Anywhere

Features enabled:
All features enabled

Errors in console: 
None to report

Screenshots/location:
![4w6wugLc0Nq](https://github.com/osrsbots-com/ORB/assets/69092673/db6c0a88-0a8c-4cc7-b7da-16a0e46f28e6)
![5RFeLeoz95l](https://github.com/osrsbots-com/ORB/assets/69092673/180e6e66-7c6b-48e0-84ce-fffa5e1333d1)

**Comment by osrsbots-com** [comment]
Fixed in **0.8.9.2 BETA** 

Follower's message will now also be in CC and match color (Red=Disabled/Blue=Enabled)
